# TCL File Generated by Component Editor 18.0
# Tue Feb 09 10:55:43 CET 2021
# DO NOT MODIFY


# 
# divider "divider" v1.0
#  2021.02.09.10:55:43
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module divider
# 
set_module_property DESCRIPTION ""
set_module_property NAME divider
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP CustomLogic
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME divider
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL divider
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file divider.vhd VHDL PATH divider.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_streaming_sink
# 
add_interface avalon_streaming_sink avalon_streaming end
set_interface_property avalon_streaming_sink associatedClock clock
set_interface_property avalon_streaming_sink associatedReset reset
set_interface_property avalon_streaming_sink dataBitsPerSymbol 8
set_interface_property avalon_streaming_sink errorDescriptor ""
set_interface_property avalon_streaming_sink firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink maxChannel 0
set_interface_property avalon_streaming_sink readyLatency 0
set_interface_property avalon_streaming_sink ENABLED true
set_interface_property avalon_streaming_sink EXPORT_OF ""
set_interface_property avalon_streaming_sink PORT_NAME_MAP ""
set_interface_property avalon_streaming_sink CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_sink SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_sink in_data data Input 128


# 
# connection point avalon_streaming_source
# 
add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock clock
set_interface_property avalon_streaming_source associatedReset reset
set_interface_property avalon_streaming_source dataBitsPerSymbol 8
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyLatency 0
set_interface_property avalon_streaming_source ENABLED true
set_interface_property avalon_streaming_source EXPORT_OF ""
set_interface_property avalon_streaming_source PORT_NAME_MAP ""
set_interface_property avalon_streaming_source CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source out_data_1 data Output 32


# 
# connection point avalon_streaming_source_1
# 
add_interface avalon_streaming_source_1 avalon_streaming start
set_interface_property avalon_streaming_source_1 associatedClock clock
set_interface_property avalon_streaming_source_1 dataBitsPerSymbol 8
set_interface_property avalon_streaming_source_1 errorDescriptor ""
set_interface_property avalon_streaming_source_1 firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source_1 maxChannel 0
set_interface_property avalon_streaming_source_1 readyLatency 0
set_interface_property avalon_streaming_source_1 ENABLED true
set_interface_property avalon_streaming_source_1 EXPORT_OF ""
set_interface_property avalon_streaming_source_1 PORT_NAME_MAP ""
set_interface_property avalon_streaming_source_1 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source_1 SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source_1 out_data_2 data Output 32


# 
# connection point avalon_streaming_source_2
# 
add_interface avalon_streaming_source_2 avalon_streaming start
set_interface_property avalon_streaming_source_2 associatedClock clock
set_interface_property avalon_streaming_source_2 dataBitsPerSymbol 8
set_interface_property avalon_streaming_source_2 errorDescriptor ""
set_interface_property avalon_streaming_source_2 firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source_2 maxChannel 0
set_interface_property avalon_streaming_source_2 readyLatency 0
set_interface_property avalon_streaming_source_2 ENABLED true
set_interface_property avalon_streaming_source_2 EXPORT_OF ""
set_interface_property avalon_streaming_source_2 PORT_NAME_MAP ""
set_interface_property avalon_streaming_source_2 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source_2 SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source_2 out_data_3 data Output 32


# 
# connection point avalon_streaming_source_3
# 
add_interface avalon_streaming_source_3 avalon_streaming start
set_interface_property avalon_streaming_source_3 associatedClock clock
set_interface_property avalon_streaming_source_3 dataBitsPerSymbol 8
set_interface_property avalon_streaming_source_3 errorDescriptor ""
set_interface_property avalon_streaming_source_3 firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source_3 maxChannel 0
set_interface_property avalon_streaming_source_3 readyLatency 0
set_interface_property avalon_streaming_source_3 ENABLED true
set_interface_property avalon_streaming_source_3 EXPORT_OF ""
set_interface_property avalon_streaming_source_3 PORT_NAME_MAP ""
set_interface_property avalon_streaming_source_3 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source_3 SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source_3 out_data_4 data Output 32

